name: Appsec Workflow Checks

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
  
jobs:
# SCAN HCC
  Gitleaks:
    name: Gitleaks Scan
    uses: ./.github/workflows/gitleaks-check.yml
    secrets: inherit
    
  TwoMS:
    name: 2MS Scan
    uses: ./.github/workflows/twoms-check.yml
    secrets: inherit
    
  Trufflehogg:
    name: Trufflehogg Scan
    uses: ./.github/workflows/Trufflehogg-check.yml
    secrets: inherit

# SAST
  SonarCloud:
     name: Sonar Cloud Scan
     uses: ./.github/workflows/sonarcloud-check.yml
     secrets: inherit

# DAST
  OWASPZAP:
     name: Owasp Zap Scan
     uses: ./.github/workflows/owaspzap-check.yml
     secrets: inherit


