name: Appsec Workflow Checks

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
  
jobs:
# SCAN HCC
  Gitleaks:
    name: Gitleaks Scan
    uses: ./.github/workflows/appsec/gitleaks-check.yml
    secrets: inherit
    
  TwoMS:
    name: 2MS Scan
    uses: ./.github/workflows/appsec/twoms-check.yml
    secrets: inherit
    
  Trufflehogg:
    name: Trufflehogg Scan
    uses: ./.github/workflows/appsec/Trufflehogg-check.yml
    secrets: inherit

# SAST
  SonarCloud:
     name: Sonar Cloud Scan
     uses: ./.github/workflows/appsec/sonarcloud-check.yml
     secrets: inherit

# IAC
  trivy:
     name: trivy Cloud Scan
     uses: ./.github/workflows/appsec/sonarcloud-check.yml
     secrets: inherit


