name: Owasp Zap (DAST) Scan

on:
  workflow_call:  # Permite que outros workflows chamem este
  workflow_dispatch:
jobs:
  dast-scan:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest
    permissions:
      issues: none
      pull-requests: none

    steps:
      # Checkout do código (caso necessário)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configurar a aplicação alvo (caso seja local)
      - name: Start Target Application
        run: |
          docker compose up -d
          sleep 30 # Tempo para garantir que o serviço esteja rodando
      
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://localhost:5001/ui'
          cmd_options: '-a'

      # Exibir o relatório de vulnerabilidades
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: /zap/wrk/output.html
