name: Sonarcloud Check Scan
on:
  workflow_call:  # Permite que outros workflows chamem este
jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones devem ser desabilitados para uma análise mais precisa
      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.scanner.skipJreProvisioning=true
            -Dsonar.host.url=http://localhost:9000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
