name: Sonarcloud Check Scan
on:
  workflow_call:  # Permite que outros workflows chamem este

jobs:
  sonarcloud:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones devem ser desabilitados para uma análise mais precisa
      
      # Aguarda o SonarQube estar pronto para receber requisições
      - name: Aguardando SonarQube iniciar
        run: |
          echo "Aguardando SonarQube iniciar..."
          until curl -s http://sonarqube:9000/api/system/status | grep -q "UP"; do
            echo "Ainda não está pronto, aguardando 5 segundos..."
            sleep 5
          done
          echo "SonarQube está pronto!"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.host.url=http://sonarqube:9000
            -Dsonar.scanner.skipJreProvisioning=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
