name: Trivy Scan
on:
  workflow_call:
  workflow_dispatch: # Permite que outros workflows chamem este
  
jobs:
  build:
    name: Trivy
    runs-on: ubuntu-20.04
    permissions:
     actions: write
     issues: write
     pull-requests: write
     contents: read
     
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: false
          vuln-type: 'os,library'
          scanners: 'vuln'
          #severity: "HIGH,CRITICAL"
