name: Trufflehogg Scan

on:
  workflow_call:  # Permite que outros workflows chamem este

jobs:
  TruffleHogg-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Truffle Hogg Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified
