name: 2MS Scan

on:
  workflow_call:  # Permite que outros workflows chamem este

jobs:
  Twoms-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # Required for 2ms to have visibility to all commit history
          fetch-depth: 0

      # ...

      - name: Run 2ms Scan
        run: docker run -v $(pwd)/.2ms.yml:/app/.2ms.yml checkmarx/2ms  --config /app/.2ms.yml

